export type UIUserAction =
  | 'cycleAssistMode'
  | 'cycleAssistTarget'
  | 'decreaseCoastHorizon'
  | 'decreaseTimeWarp'
  | 'increaseCoastHorizon'
  | 'increaseTimeWarp'
  | 'loadDebugSnapshot'
  | 'promptConfirm'
  | 'resetScenario'
  | 'saveDebugSnapshot'
  | 'toggleDebugMode'
  | 'toggleFpsIndicator'
  | 'toggleNoGravityDebug'
  | 'togglePerformanceDebug'
  | 'zoomIn'
  | 'zoomOut'
